#!/bin/bash
# Copyright (c) 2026 LG Electronics, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# Static analysis and multi-architecture warning sweep for luna-downloadmgr.
#
# The point of having this in the tree is that "it builds" is not the same as
# "it builds clean everywhere": uint64_t is unsigned long long on armv7 and
# unsigned long on aarch64/x86-64, so a whole class of format-string bug is
# invisible unless a 32-bit target is part of the sweep.
#
# Needs a sysroot with the component's dependencies. Point --sysroot at one
# (an OE recipe-sysroot works) and name the cross compiler prefix:
#
#   tools/analyze.sh --sysroot /path/to/recipe-sysroot \
#                    --cross   /path/to/bin/arm-webos-linux-gnueabi- \
#                    --arch    armv7
#
# With no --sysroot it runs the source-only checkers (cppcheck) against the
# host, which still catches a useful amount without any cross setup.
#
# Checks:
#   cppcheck     --enable=all, exhaustive
#   clang-tidy   bugprone-*, cert-*, clang-analyzer-*, concurrency-*, ...
#   gcc          -fanalyzer
#   clang        --analyze
#   warnings     -Wall -Wextra -Wshadow -Wformat=2 per architecture

set -u

SRC_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${TMPDIR:-/tmp}/ldm-analyze.$$"
SYSROOT=""
CROSS=""
ARCH="host"
TUNE=""
JOBS="$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)"
ONLY=""
KEEP=0

usage() {
    sed -n '18,40p' "$0" | sed 's/^# \?//'
    cat <<EOF

Options:
  --sysroot DIR     target sysroot containing the dependencies
  --cross PREFIX    cross compiler prefix, e.g. .../aarch64-webos-linux-
  --arch NAME       label for the report, and picks default -march flags
                    (armv7|aarch64|x86_64|host)
  --tune "FLAGS"    override the -march/-mtune flags for this arch
  --out DIR         where to write the reports (default a temp dir)
  --only LIST       comma-separated subset of: cppcheck,tidy,gccanalyzer,
                    clanganalyzer,warnings
  --keep            keep the output directory even on success
  -j N              parallelism (default $JOBS)
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --sysroot) SYSROOT="$2"; shift 2 ;;
        --cross)   CROSS="$2"; shift 2 ;;
        --arch)    ARCH="$2"; shift 2 ;;
        --tune)    TUNE="$2"; shift 2 ;;
        --out)     OUT_DIR="$2"; shift 2 ;;
        --only)    ONLY="$2"; shift 2 ;;
        --keep)    KEEP=1; shift ;;
        -j)        JOBS="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
done

if [ -z "$TUNE" ]; then
    case "$ARCH" in
        armv7)   TUNE="-march=armv7ve -mfpu=neon -mfloat-abi=hard -mthumb" ;;
        aarch64) TUNE="-march=armv8-a+crc" ;;
        x86_64)  TUNE="-march=nehalem -mtune=generic" ;;
        *)       TUNE="" ;;
    esac
fi

want() {
    [ -z "$ONLY" ] && return 0
    case ",$ONLY," in *",$1,"*) return 0 ;; esac
    return 1
}

mkdir -p "$OUT_DIR"
FINDINGS=0

log()  { printf '\n=== %s\n' "$*"; }
note() { printf '    %s\n' "$*"; }

# ------------------------------------------------------------------ toolchain

CXX="g++"
CC="gcc"
[ -n "$CROSS" ] && { CXX="${CROSS}g++"; CC="${CROSS}gcc"; }

PKGFLAGS=""
if [ -n "$SYSROOT" ]; then
    export PKG_CONFIG_SYSROOT_DIR="$SYSROOT"
    export PKG_CONFIG_LIBDIR="$SYSROOT/usr/lib/pkgconfig:$SYSROOT/usr/share/pkgconfig"
    unset PKG_CONFIG_PATH
    PKGS="glib-2.0 gthread-2.0 luna-prefs luna-service2 pbnjson_cpp PmLogLib libcurl sqlite3"
    if ! PKGFLAGS="$(pkg-config --cflags $PKGS 2>"$OUT_DIR/pkgconfig.err")"; then
        echo "pkg-config failed against $SYSROOT:" >&2
        cat "$OUT_DIR/pkgconfig.err" >&2
        exit 2
    fi
fi

# webospaths.h is generated by webos_include_install_paths() at configure time.
# The analysers need it, and only the three macros the code actually uses.
GEN="$OUT_DIR/gen"
mkdir -p "$GEN"
cat > "$GEN/webospaths.h" <<'EOF'
// generated by tools/analyze.sh, mirroring webos_include_install_paths()
#define WEBOS_INSTALL_BINDIR "/usr/bin"
#define WEBOS_INSTALL_SBINDIR "/usr/sbin"
#define WEBOS_INSTALL_WEBOS_SYSCONFDIR "/etc/palm"
#define WEBOS_INSTALL_SYSCONFDIR "/etc"
#define WEBOS_INSTALL_LOCALSTATEDIR "/var"
#define WEBOS_INSTALL_DATADIR "/usr/share"
#define WEBOS_INSTALL_PREFIX "/usr"
EOF

INCLUDES="-I$SRC_DIR/src -I$GEN"
BASE_WARN="-Wall -Wextra -Wshadow -Wformat=2 -Wpointer-arith -Wcast-align -Wno-unused-parameter"
BASE_DEFS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"

SOURCES="$(ls "$SRC_DIR"/src/*.cpp "$SRC_DIR"/src/*.c 2>/dev/null)"

# -------------------------------------------------------------------- cppcheck

if want cppcheck && command -v cppcheck >/dev/null 2>&1; then
    log "cppcheck (exhaustive)"
    cppcheck --enable=all --inconclusive --check-level=exhaustive \
             --std=c++17 --language=c++ \
             --suppress=missingIncludeSystem --suppress=checkersReport \
             --suppress=unusedFunction \
             $INCLUDES \
             --template='{file}:{line}: [{severity}/{id}] {message}' \
             "$SRC_DIR/src" > "$OUT_DIR/cppcheck.txt" 2>&1
    # style/performance noise is not what this gate is for
    n="$(grep -cE '\[(error|warning)/' "$OUT_DIR/cppcheck.txt" || true)"
    note "$n error/warning findings -> $OUT_DIR/cppcheck.txt"
    grep -E '\[(error|warning)/' "$OUT_DIR/cppcheck.txt" | sed 's|^|    |' | head -40
    FINDINGS=$((FINDINGS + n))
elif want cppcheck; then
    note "cppcheck not installed, skipping"
fi

# ------------------------------------------------------------------ clang-tidy

if want tidy && command -v clang-tidy >/dev/null 2>&1 && [ -n "$SYSROOT" ]; then
    log "clang-tidy"
    # clang needs the cross libstdc++ headers spelled out
    CXXINC=""
    for d in "$SYSROOT"/usr/include/c++/*; do
        [ -d "$d" ] || continue
        CXXINC="-isystem $d"
        for t in "$d"/*-linux*; do [ -d "$t" ] && CXXINC="$CXXINC -isystem $t"; done
        [ -d "$d/backward" ] && CXXINC="$CXXINC -isystem $d/backward"
    done

    CDB="$OUT_DIR/cdb"
    mkdir -p "$CDB"
    {
        printf '[\n'
        first=1
        for f in $SOURCES; do
            [ $first -eq 1 ] || printf ',\n'
            first=0
            printf '{"directory":"%s","file":"%s","command":"clang++ --sysroot=%s %s -x c++ -std=gnu++17 %s %s %s -c %s -o /dev/null"}' \
                   "$SRC_DIR" "$f" "$SYSROOT" "$CXXINC" "$BASE_DEFS" "$INCLUDES" "$PKGFLAGS" "$f"
        done
        printf '\n]\n'
    } > "$CDB/compile_commands.json"

    clang-tidy -p "$CDB" --quiet \
        --checks='-*,bugprone-*,cert-*,clang-analyzer-*,concurrency-*,misc-*,performance-*,portability-*,readability-misleading-indentation,cppcoreguidelines-init-variables,cppcoreguidelines-slicing,cppcoreguidelines-virtual-class-destructor,-misc-include-cleaner,-misc-unused-parameters,-misc-non-private-member-variables-in-classes,-misc-use-anonymous-namespace,-misc-const-correctness,-misc-use-internal-linkage,-bugprone-easily-swappable-parameters,-bugprone-narrowing-conversions,-bugprone-assignment-in-if-condition,-bugprone-branch-clone,-bugprone-implicit-widening-of-multiplication-result,-performance-unnecessary-value-param,-performance-avoid-endl' \
        $SOURCES > "$OUT_DIR/clang-tidy.txt" 2>"$OUT_DIR/clang-tidy.err"
    n="$(grep -c 'warning:' "$OUT_DIR/clang-tidy.txt" || true)"
    note "$n findings -> $OUT_DIR/clang-tidy.txt"
    grep 'warning:' "$OUT_DIR/clang-tidy.txt" | grep -v "$SYSROOT" | sed 's|^|    |' | head -40
    FINDINGS=$((FINDINGS + n))
elif want tidy; then
    note "clang-tidy needs --sysroot and clang-tidy installed, skipping"
fi

# --------------------------------------------------------------- gcc -fanalyzer

if want gccanalyzer && [ -n "$SYSROOT" ] && command -v "$CXX" >/dev/null 2>&1; then
    log "gcc -fanalyzer ($ARCH)"
    : > "$OUT_DIR/gcc-analyzer.txt"
    for f in $SOURCES; do
        "$CXX" --sysroot="$SYSROOT" $TUNE -x c++ -std=gnu++17 -fanalyzer \
               -fsyntax-only $BASE_DEFS $INCLUDES $PKGFLAGS "$f" \
               >> "$OUT_DIR/gcc-analyzer.txt" 2>&1
    done
    n="$(grep -c 'warning:.*-Wanalyzer' "$OUT_DIR/gcc-analyzer.txt" || true)"
    note "$n analyzer findings -> $OUT_DIR/gcc-analyzer.txt"
    grep 'warning:.*-Wanalyzer' "$OUT_DIR/gcc-analyzer.txt" | sed 's|^|    |' | head -20
    FINDINGS=$((FINDINGS + n))
elif want gccanalyzer; then
    note "gcc -fanalyzer needs --sysroot, skipping"
fi

# ------------------------------------------------------------- clang --analyze

if want clanganalyzer && [ -n "$SYSROOT" ] && command -v clang++ >/dev/null 2>&1; then
    log "clang --analyze"
    CXXINC=""
    for d in "$SYSROOT"/usr/include/c++/*; do
        [ -d "$d" ] || continue
        CXXINC="-isystem $d"
        for t in "$d"/*-linux*; do [ -d "$t" ] && CXXINC="$CXXINC -isystem $t"; done
        [ -d "$d/backward" ] && CXXINC="$CXXINC -isystem $d/backward"
    done
    : > "$OUT_DIR/clang-analyzer.txt"
    for f in $SOURCES; do
        clang++ --sysroot="$SYSROOT" $CXXINC --analyze --analyzer-output text \
                -x c++ -std=gnu++17 $BASE_DEFS $INCLUDES $PKGFLAGS "$f" -o /dev/null \
                >> "$OUT_DIR/clang-analyzer.txt" 2>&1
    done
    n="$(grep -c 'warning:' "$OUT_DIR/clang-analyzer.txt" || true)"
    note "$n findings -> $OUT_DIR/clang-analyzer.txt"
    grep 'warning:' "$OUT_DIR/clang-analyzer.txt" | grep -v "$SYSROOT" | sed 's|^|    |' | head -20
    FINDINGS=$((FINDINGS + n))
elif want clanganalyzer; then
    note "clang --analyze needs --sysroot, skipping"
fi

# ----------------------------------------------------------------- warning gate

if want warnings && [ -n "$SYSROOT" ] && command -v "$CXX" >/dev/null 2>&1; then
    log "compiler warnings ($ARCH, $CXX)"
    : > "$OUT_DIR/warnings-$ARCH.txt"
    rc=0
    for f in $SOURCES; do
        "$CXX" --sysroot="$SYSROOT" $TUNE -x c++ -std=gnu++17 \
               $BASE_WARN $BASE_DEFS $INCLUDES $PKGFLAGS \
               -fsyntax-only "$f" >> "$OUT_DIR/warnings-$ARCH.txt" 2>&1 || rc=1
    done
    # Deprecation notices come from libcurl's form API and pbnjson, not from
    # this code, and need an API migration rather than a fix; count them
    # separately so they cannot mask a real regression.
    dep="$(grep -c 'deprecated' "$OUT_DIR/warnings-$ARCH.txt" || true)"
    own="$(grep 'warning:' "$OUT_DIR/warnings-$ARCH.txt" | grep -vc 'deprecated' || true)"
    note "$own own warnings, $dep third-party deprecation notices"
    note "-> $OUT_DIR/warnings-$ARCH.txt"
    grep 'warning:' "$OUT_DIR/warnings-$ARCH.txt" | grep -v 'deprecated' | sed 's|^|    |' | head -40
    [ "$rc" = 0 ] || { note "COMPILE FAILED"; FINDINGS=$((FINDINGS + 1)); }
    FINDINGS=$((FINDINGS + own))
elif want warnings; then
    note "warning gate needs --sysroot, skipping"
fi

# ----------------------------------------------------------------------- report

printf '\n==============================================\n'
printf 'arch=%s  findings=%s\n' "$ARCH" "$FINDINGS"
printf 'reports in %s\n' "$OUT_DIR"

if [ "$FINDINGS" = 0 ] && [ "$KEEP" = 0 ]; then
    rm -rf "$OUT_DIR"
    printf '(clean; removed the report directory, pass --keep to retain it)\n'
    exit 0
fi
exit 1
